name: Morpheus Automation_merchant_1

on:
  push:
  schedule:
    - cron: '0 8,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        address: ["2MvFAyt4erKgPRKACpuuMzUximfLBGcHREM", "2MvDTx5WQEQXcXHGWb5hPuxjQ75Af3b62nn", "2MvboPRW4UV3gx3EEzHQsgtPFXjQHL2E9Kp", "2Mv2sY1Tz5Z7yjLehg4yF2GxehxfTVbU44P", "2MuqxmUfa2b2kJZRkniuUbTBJDd1avCgwAf", "2MzTRNf7oyTFkE5nT5JemjHwdh9JoXQw1y7"]
    steps:
      - uses: actions/checkout@v2
      - name: Cache requirements
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Test with behave
        run: |
          python testnet-faucet.mempool.co.py "${{ matrix.address }}"
