name: Morpheus Automation_merchant_internal_wallet

on:
  schedule:
    - cron: '* 0,14 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        address: ["2MwcNnfLeYVA4BvniJukCmtR3vYbJZo4ZJg", "2MvZSSJ4aKpC5pJHyiVyHgFvio37r2RQeYi", "2MvXMLKWXzScowZBfL4uhvZsyLDjzmPx5fe", "2MvXcr93s1u8ubDQUxrEdeFMboVYx32Vh2P", "2MvQzihS1yVxrbrTUm3NTL1VcC5FSp2ipS3", "2NE7G2AWic1tZTcH3qxsd5P91FCP8Vgw2uk"]
    steps:
      - uses: actions/checkout@v2
      - name: Cache requirements
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Test with behave
        run: |
          python testnet-faucet.mempool.co.py "${{ matrix.address }}"
