name: Test

on:
  push:
  schedule:
    - cron: '0 */2 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        address: ["2N1xtrVTk1uc4Pm4so2VNxiCp6bD8v9T7Sg", "2Mw8jFsye3Wr45tjykdrk97aVXzRMKoyBR2", "2NDncyedzXvD8k7DUfb8FNTYCqMTQMoLZWY", "2NDNe1RTTygdrRmBEaKC9mvSXQnsKCwTacg", "2NDngd91ZK4fnKEmTz8ytUoCRXb86R32Ttf", "2NDNiBzcMqLXK8v61HWC5H7a5ngmgGDA1Ww", "2NDNmYLjWjPGk6VBuYpmHDwBFmmXQkC5Wq4", "2NDNrWJyQxKh4HXg14rYsmtqkV7dhNGdMrF", "2NDnsHr9EdKGgRRm2HhCL1xnQ8mJttZV2kj", "2NDNTr7g691nhty33kJw3GwFa9vEoAfCg5X", "2MsLwbZuFiLQyNftAxCp6egxxjgStycaghR", "2NCmg5QpXztt8cwGGTdDTQ1NCNB4QhiPcrR", "2NCsKKNPhw1qR2akzo8m8iRMZVAp5aNmFSW", "2NCsKKNPhw1qR2akzo8m8iRMZVAp5aNmFSW", "2MzV1C5zH28njscFmot9J9GXSsxXu14Wag7", "2N1sNfgBrJjzx8u6JpUYxjtNnyAdK463yWq", "2MvXFnFaKHDb8rPcMimTd8ajCm3mXgDg1Jo", "2MxffVmjGnTmoJ3xd1t68ca3f3ZzNu9B4K4", "2NB7m3txJTQrpGq1Xyi4J9pnyvwwNxSG8RU", "2N5pNVYKiEjT3LSKoTBNRNWLyCr8Poia48j", "2N4oDr4DL7Lue6GQPaB9RLdb2JvZn8Fb4Xy", "2MsLwbZuFiLQyNftAxCp6egxxjgStycaghR", "2Mvyq38P5buMdzw9FU1WTAFgDXeMYckswiz", "2Mw6LEnmNY6D7jCqKuEtnEf4gZ9c5VHKctf", "2N4VP3NmHwNQAmfv4wvjXbcCtA9xMzsfYNA", 2N4WD5DS3b526nsMXEJUC4v7RDPBQUwAc3D", "2MtgLeGjbiRYFAfLhmw7625ghCo7k4ebzc6", "2MtMMftrZLsNA1GXpeLs2po3LmbW2P3VkZm", "2N88znXgRnZ29p4MnmQMWBzqdcyshVbLq5e", "2NC6ksMkRpt3NumF1mMGo5KgGeRzd2TLzXd", "2MyLWF5rwACVZmBFCChEn2mCMUXsbbNoNSw", "2Mw7wLUSgcxAqxdEwtxXmwtzaSHcZgxYFVt", "2NAusN9npJdJut1qqsXdQK8tNGihAmjJkn2", "2NBWqJsLBtonyQe8U3N5wsavRgxEaAG2t5S", "2N7hM2wjPGjAGUqZjT5DJWmKGyYjXqtpxD3", "2MzcgunvoCYV5SsAhnWaWUkgcmdYozWDsrq", "2Mt4SaPRs3J8xkvsfSGmnjQh9qihNXTy6CE", "2N83LxATzLrcdnTkMTCUHGmmCEpsnCkC5T5", "2N7Ek5JL3nsy1AaAtdgKDizTx4ZwUG9aCfj", "2N1pcDrwWmVzbZC9m9HZrnCYc1N4LQsQwMz", "2MyYWbiKr3UBLRAMfjvryqPThdwiKsek4pa", "2Mxe4i459UwkKTpx8edCYzSsVVuzUdVxSxS", "2NBABAmXjHaeNszikrJnoCXbgufUvRf1Dar", "2N5cdrf1bUxPRntKPKA5Kptr9WBJXNFZEEn", "2NAJpxmfEsBG68b64fbmRT7LGwmUn5z9pJv", "2NEBwqTRuNwgrwyTJokA4eabEMV7EW4C7dA", "2NANgiSUbf9wRG5CKwyfDS98wTSE8ucRjco", "2MsGp19WMSCzxHf6VuSgpexTfNRoRDQ6sQE", "2MuNy7X2hJFQi49Y4EFXAt8u7TRuxvzjUBJ", "2NAgceGZmSBTD9omeLR5s2BiALXZZwb1ciW", "2NCyfKhFsGntjy5HHm2rpjihYmVfQbhVPu5", "2N74qMuUkfv3XbAZHUwYbYgpcU71yMDQe2x", 2N74qMuUkfv3XbAZHUwYbYgpcU71yMDQe2x", "2N1BxhN4j8Nff7XJzRSTPQe5nTzybDnZ5S9", "2N4YPQVhooJwPDgwZxjn6jeDDJyko4CLD58", "2N4oJSkk2ZeWtGXzF51EvfF7vMhjutzT4H9", "2N4WQBD7f3fuNiTtKtJd3HETtxd2rzRGkpU", "2N9shs4rJmFXein7fZQKND3S7x75P12qKR2", "2Mxcu2WWEnUPmj88rSMRsWsJkBh5q5ryfST", "2N4UwxXpD7dc5ZHXnCttxFHCzpkZ6qQD9d8", "2MywkhfyqathUGaN5xB36xXkvnXMHPfbdHx"]
    steps:
      - uses: actions/checkout@v2
      - name: Cache requirements
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Test with behave
        run: |
          python testnet-faucet.mempool.co.py "${{ matrix.address }}"
