name: Morpheus internal_001

on:
  schedule:
    - cron: '0 10,20 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        address: ["2N31d2rdchHp5UexuexUv5gx7k4AmqW8bzm", "2MzJYfqGAej7LiJjV9c1YdfEFFpUQUeR6mM", "2MzGzExbhCB8zThhkzVN9Dnwg9Nxok9svKR", "2My5oRusDDfANMoLxiuirxwLvVt8yheB2Lk", "2MxwnLXkpMD6FCuzyFBwANhcG83r7se73Gu", "2N3FUnNFD5F1a87piTQfPoXT7JLgZwrMLby"]
    steps:
      - uses: actions/checkout@v2
      - name: Cache requirements
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Test with behave
        run: |
          python testnet-faucet.mempool.co.py "${{ matrix.address }}"
