name: Neo internal_001

on:
  schedule:
    - cron: '40 */2 1-29/5 * *'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        address: ["2N1xtrVTk1uc4Pm4so2VNxiCp6bD8v9T7Sg", "2Mw8jFsye3Wr45tjykdrk97aVXzRMKoyBR2", "2NDncyedzXvD8k7DUfb8FNTYCqMTQMoLZWY", "2NDNe1RTTygdrRmBEaKC9mvSXQnsKCwTacg", "2NDngd91ZK4fnKEmTz8ytUoCRXb86R32Ttf", "2NDNiBzcMqLXK8v61HWC5H7a5ngmgGDA1Ww", "2NDNmYLjWjPGk6VBuYpmHDwBFmmXQkC5Wq4", "2NDNrWJyQxKh4HXg14rYsmtqkV7dhNGdMrF", "2NDnsHr9EdKGgRRm2HhCL1xnQ8mJttZV2kj", "2NDNTr7g691nhty33kJw3GwFa9vEoAfCg5X"]
    steps:
      - uses: actions/checkout@v2
      - name: Cache requirements
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Test with behave
        run: |
          python testnet-faucet.mempool.co.py "${{ matrix.address }}"
