name: Neo external_002

on:
  schedule:
    - cron: '50 */2 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        address: ["2MsLwbZuFiLQyNftAxCp6egxxjgStycaghR", "2Mvyq38P5buMdzw9FU1WTAFgDXeMYckswiz", "2Mw6LEnmNY6D7jCqKuEtnEf4gZ9c5VHKctf", "2N4VP3NmHwNQAmfv4wvjXbcCtA9xMzsfYNA", 2N4WD5DS3b526nsMXEJUC4v7RDPBQUwAc3D", "2MtgLeGjbiRYFAfLhmw7625ghCo7k4ebzc6", "2MtMMftrZLsNA1GXpeLs2po3LmbW2P3VkZm", "2N88znXgRnZ29p4MnmQMWBzqdcyshVbLq5e", "2NC6ksMkRpt3NumF1mMGo5KgGeRzd2TLzXd", "2MyLWF5rwACVZmBFCChEn2mCMUXsbbNoNSw"]
    steps:
      - uses: actions/checkout@v2
      - name: Cache requirements
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Test with behave
        run: |
          python testnet-faucet.mempool.co.py "${{ matrix.address }}"
